# Model parameters
model_type: 'frac1'
param_ini: [0.599, 3.669, -0.048, 0.020, 0.80, 0.11]
param_low: [0.2, 0.0, -0.2, 0.0, 0.3, 0.0]
param_upp: [1.0, 8.0, 0.0, 0.2, 1.0, 0.3]
param_sig: [0.05, 0.1, 0.02, 0.005, 0.05, 0.05]

# MCMC Runs
mcmc_prefix: 'asap_smdpl'
mcmc_nsamples: 2
mcmc_nthreads: 2
mcmc_nburnin: 2
mcmc_nwalkers: 16
mcmc_smf_only: False
mcmc_wl_only: False
mcmc_wl_weight: 1.0

# HSC data part
obs_dir: '../data/s16a_massive_wide2'
obs_cat: 's16a_wide2_massive_fsps1_imgsub_use_short.fits'
obs_wl_sample: 's16a_wide2_massive_boxbin3_default'

# Volume:
obs_area: 145.0

# Cosmology
obs_h0: 0.70
obs_omega_m: 0.307

# SMF
obs_smf_inn: 's16a_wide2_massive_smf_m10_11.5.fits'
obs_smf_tot: 's16a_wide2_massive_smf_mmax_11.5.fits'
obs_smf_full_fits: 'primus_smf_z0.3_0.4.fits'

# Useful information in the catalog
obs_z_col: 'z_best'
obs_minn_col: 'logm_10'
obs_mtot_col: 'logm_max'

# UniverseMachine
um_dir: '../data/s16a_massive_wide2/um2'
um_lbox: 400.0
um_h0: 0.678
um_omega_m: 0.307
um_model: 'um_smdpl_0.7124_new_vagc_mpeak_11.5.npy'
um_wl_cat: 'um_smdpl_0.7124_new_vagc_mpeak_11.5_50m_r_0.08_50_22bins.npy'
um_min_mvir: 11.5
um_redshift: 0.3637
um_wl_minr: 0.08
um_wl_maxr: 50.0
um_wl_nbin: 22
um_wl_add_stellar: False
um_mtot_nbin: 80
um_mtot_nbin_min: 7
um_min_nobj_per_bin: 30
um_min_scatter: 0.01
um_halo_col: 'logmh_vir'
um_star_col: 'logms_tot'
